### ISSUE TITLE
Respect git config values for remote and pushRemote

### ISSUE THREAD

**Issue by Machine-Maker** [romkatv/gitstatus#292] opened 2022-01-10 03:50 UTC
When using the gh cli to checkout a PR from some repository, instead of adding the remote and then checking out the branch, it adds config entries for that specific branch telling git where pushes should go. Issue here is, that gitstatus (via powerlevel10k) isn't showing commits ahead or behind that remote/branch, probably because it doesn't know it has one cause its not checking the local git config.

**Comment by romkatv** [comment] 2022-01-10 07:24
What do I need to do to reproduce this?

**Comment by Machine-Maker** [comment] 2022-01-10 10:31
Have a GitHub repo that has an open PR from a fork, not a different branch in the same repo. Then use the GitHub cli tool to checkout that pr, so `gh pr checkout ####`. You can then add a commit. gitstatus should say you are 1 ahead, but it doesn’t. And a `git push` succeeds in pushing to the branch the PR is from.

**Comment by romkatv** [comment] 2022-01-10 10:40
I might take a look at it but not soon. Maybe in a month or two.

If you can provide more specific instructions (commands I can run, which don't require `gh` and don't use Internet), it'll speed things up considerably.

**Comment by romkatv** [comment] 2022-09-21 09:21
Closing because I don't intend to do anything here.

**Closed by romkatv** 2022-09-21 09:21 UTC
