### ISSUE TITLE
Support for darwin arm64

### ISSUE THREAD

**Issue by mikelxc** [romkatv/gitstatus#188] opened 2020-11-17 05:40 UTC
No prebuilt packages available for Apple Silicon Macs, and when try to build it on an Apple Silicon Mac, there's an error of `./build: line 482: unexpected EOF while looking for matching `''`

**Comment by mikelxc** [comment] 2020-11-17 06:27
Related issue #167 . Successfully finished building after manually building libiconv with my [workaround method](https://github.com/mikelxc/Workarounds-for-ARM-mac/blob/main/README.md). Then change the part of code in "build" file referencing libiconv to /opt/homebrew (instead of the default installation for x86 Macs) to match install location.

An easier method without changing the code would be 
``` bash
brew install -s libiconv
export LDFLAGS="-L/opt/homebrew/opt/libiconv/lib"
export CPPFLAGS="-I/opt/homebrew/opt/libiconv/include"
```

Then I manually builded libgit2 from source.

After these preparations, I can now run `zsh ./build -w -s` to finish the build.

To save trouble, I've included the binary for arm-based Mac.
[gitstatusd.zip](https://github.com/romkatv/gitstatus/files/5551642/gitstatusd.zip)

**Comment by romkatv** [comment] 2020-11-17 07:30
Thanks for the info!

I don't yet have access to a darwin-aarch64 machine, so I cannot provide official gitstatusd binaries for it. I've updated metadata in gitstatus to fall back to `gitstatusd-darwin-x86_64` on darwin-aarch64. Could you verify that it works?

```zsh
git clone --depth=1 https://github.com/romkatv/gitstatus.git /tmp/gitstatus
cd /tmp/gitstatus
zsh -fc 'unset -m "GITSTATUS_*"; GITSTATUS_CACHE_DIR="$PWD"/usrbin ./install -f'
./usrbin/gitstatusd-darwin-x86_64 --version
```

**Comment by romkatv** [comment] 2020-11-17 08:32
> there's an error of `./build: line 482: unexpected EOF while looking for matching `''`

This is caused by a bug in bash that has been fixed many years ago but will apparently never make it into macOS. It chokes on this:

```shell
cat <<\END
'
END
```

As you've discovered, you can use any other interpreter compatible with sh to run the script. Zsh will do.

I've committed a workaround that should make `build` work with the stock bash from macOS. I haven't tested it though.

**Comment by romkatv** [comment] 2020-11-17 09:01
> Then change the part of code in "build" file referencing libiconv to /opt/homebrew (instead of the default installation for x86 Macs) to match install location.

I've updated `build` to invoke `brew --prefix` instead of hardcoding `/usr/local` or `/opt/homebrew` there.

**Comment by mikelxc** [comment] 2020-11-17 11:25
> Thanks for the info!
> 
> I don't yet have access to a darwin-aarch64 machine, so I cannot provide official gitstatusd binaries for it. I've updated metadata in gitstatus to fall back to `gitstatusd-darwin-x86_64` on darwin-aarch64. Could you verify that it works?
> 
> ```shell
> git clone --depth=1 https://github.com/romkatv/gitstatus.git /tmp/gitstatus
> cd /tmp/gitstatus
> zsh -fc 'unset -m "GITSTATUS_*"; GITSTATUS_CACHE_DIR="$PWD"/usrbin ./install -f'
> ./usrbin/gitstatusd-darwin-x86_64 --version
> ```

This is what I get after running these commands
```
zsh -fc 'unset -m "GITSTATUS_*"; GITSTATUS_CACHE_DIR="$PWD"/usrbin ./install -f'
[gitstatus] error: no gitstatusd found for darwin arm64
```

**Comment by romkatv** [comment] 2020-11-17 11:34
Oh, they call it arm64 rather than aarch64? Fixed. Please try the same command again after removing `/tmp/gitstatus` (or just `git pull` in there).

**Comment by mikelxc** [comment] 2020-11-17 11:39
> Oh, they call it arm64 rather than aarch64? Fixed. Please try the same command again after removing `/tmp/gitstatus` (or just `git pull` in there).

The naming can be tricky sometimes. It works on my machine. Now I get the correct version number.

**Comment by romkatv** [comment] 2020-11-17 11:44
Thanks for verifying!

I'll leave things as they are for now. gitstatus and powerlevel10k should work on darwin-arm64 via rosetta 2. When I manage to get access to this platform, I'll build a native arm64 binary.

**Comment by mikelxc** [comment] 2020-11-17 11:50
> Thanks for verifying!
> 
> I'll leave things as they are for now. gitstatus and powerlevel10k should work on darwin-arm64 via rosetta 2. When I manage to get access to this platform, I'll build a native arm64 binary.

Free free to use [the one compiled on my machine](https://github.com/romkatv/gitstatus/files/5551642/gitstatusd.zip) if you don't mind.

**Comment by romkatv** [comment] 2020-11-17 11:51
I don't distribute binaries that I haven't been myself in a clean environment.

**Comment by mikelxc** [comment] 2020-11-17 11:53
That's fair. And Rosetta2 works for now. Thank you for your efforts and for making creating such a wonderful tool!

**Comment by romkatv** [comment] 2020-11-17 11:55
You are welcome.

Thanks for filing the issue and testing my fixes!

**Closed by romkatv** 2020-11-17 11:55 UTC
