### ISSUE TITLE
[ERROR]: gitstatus failed to initialize on Cygwin

### ISSUE THREAD

**Issue by kgraefe** [romkatv/gitstatus#94] opened 2020-01-15 09:37 UTC
Every now and than gitstatus does not initialize. Reopening the Cygwin shell fixes the problem most of the time. The failing command is always the same, though:
```
[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  The content of /tmp/gitstatus.1425.xtrace.1579080686.1866104603.25223 (gitstatus_start_impl xtrace):

    +gitstatus_start_impl:6> ((  daemon_pid == -1  ))
    +gitstatus_start_impl:7> local daemon=/cygdrive/c/Users/k.graefe/dotfiles/shell/powerlevel10k/gitstatus/bin/gitstatusd-cygwin_nt-10.0-x86_64 os
    +gitstatus_start_impl:8> [[ -n /cygdrive/c/Users/k.graefe/dotfiles/shell/powerlevel10k/gitstatus/bin/gitstatusd-cygwin_nt-10.0-x86_64 ]]
    +gitstatus_start_impl:15> [[ -x /cygdrive/c/Users/k.graefe/dotfiles/shell/powerlevel10k/gitstatus/bin/gitstatusd-cygwin_nt-10.0-x86_64 ]]
    +gitstatus_start_impl:17> lock_file=/tmp/gitstatus.1425.lock.1579080686.1888432503.4060
    +gitstatus_start_impl:18> echo -n
    +gitstatus_start_impl:19> zsystem flock -f lock_fd /tmp/gitstatus.1425.lock.1579080686.1888432503.4060
    +gitstatus_start_impl:21> req_fifo=/tmp/gitstatus.1425.req.1579080686.1897628307.13117
    +gitstatus_start_impl:22> resp_fifo=/tmp/gitstatus.1425.resp.1579080686.1897997856.13973
    +gitstatus_start_impl:23> mkfifo /tmp/gitstatus.1425.req.1579080686.1897628307.13117 /tmp/gitstatus.1425.resp.1579080686.1897997856.13973
    +gitstatus_start_impl:25> local -i threads=12
    +gitstatus_start_impl:26> ((  threads > 0 ))
    +gitstatus_start_impl:36> local -a daemon_args=( '--lock-fd=3' '--parent-pid=1425' '--num-threads=12' '--max-num-staged=-1' '--max-num-unstaged=-1' '--max-num-conflicted=-1' '--max-num-untracked=-1' '--dirty-max-index-size=-1' '--log-level=DEBUG' )
    +gitstatus_start_impl:48> local cmd=$'\n        exec >&4\n        echo $$\n        /cygdrive/c/Users/k.graefe/dotfiles/shell/powerlevel10k/gitstatus/bin/gitstatusd-cygwin_nt-10.0-x86_64 --lock-fd=3 --parent-pid=1425 --num-threads=12 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --log-level=DEBUG\n        if [[ $? != (0|10) && $? -le 128 && -f /cygdrive/c/Users/k.graefe/dotfiles/shell/powerlevel10k/gitstatus/bin/gitstatusd-cygwin_nt-10.0-x86_64-static ]]; then\n          /cygdrive/c/Users/k.graefe/dotfiles/shell/powerlevel10k/gitstatus/bin/gitstatusd-cygwin_nt-10.0-x86_64-static --lock-fd=3 --parent-pid=1425 --num-threads=12 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --log-level=DEBUG\n        fi\n        echo -nE $\'bye\\x1f0\\x1e\''
    +gitstatus_start_impl:56> local setsid=/usr/bin/setsid
    +gitstatus_start_impl:57> [[ -x /usr/bin/setsid ]]
    +gitstatus_start_impl:57> setsid=/usr/bin/setsid
    +gitstatus_start_impl:62> local zsh=/usr/bin/zsh
    +gitstatus_start_impl:63> [[ -x /usr/bin/zsh ]]
    +gitstatus_start_impl:64> cmd='cd /; read; /usr/bin/setsid /usr/bin/zsh -dfxc $'\''\n'\''\ \ \ \ \ \ \ \ exec\ \>\&4$'\''\n'\''\ \ \ \ \ \ \ \ echo\ \$\$$'\''\n'\''\ \ \ \ \ \ \ \ /cygdrive/c/Users/k.graefe/dotfiles/shell/powerlevel10k/gitstatus/bin/gitstatusd-cygwin_nt-10.0-x86_64\ --lock-fd=3\ --parent-pid=1425\ --num-threads=12\ --max-num-staged=-1\ --max-num-unstaged=-1\ --max-num-conflicted=-1\ --max-num-untracked=-1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ \ \ if\ \[\[\ \$\?\ \!=\ \(0\|10\)\ \&\&\ \$\?\ -le\ 128\ \&\&\ -f\ /cygdrive/c/Users/k.graefe/dotfiles/shell/powerlevel10k/gitstatus/bin/gitstatusd-cygwin_nt-10.0-x86_64-static\ \]\]\;\ then$'\''\n'\''\ \ \ \ \ \ \ \ \ \ /cygdrive/c/Users/k.graefe/dotfiles/shell/powerlevel10k/gitstatus/bin/gitstatusd-cygwin_nt-10.0-x86_64-static\ --lock-fd=3\ --parent-pid=1425\ --num-threads=12\ --max-num-staged=-1\ --max-num-unstaged=-1\ --max-num-conflicted=-1\ --max-num-untracked=-1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ \ \ fi$'\''\n'\''\ \ \ \ \ \ \ \ echo\ -nE\ \$\'\''bye\\x1f0\\x1e\'\'' &!; rm -f /tmp/gitstatus.1425.req.1579080686.1897628307.13117 /tmp/gitstatus.1425.resp.1579080686.1897997856.13973 /tmp/gitstatus.1425.lock.1579080686.1888432503.4060'
    +gitstatus_start_impl:70> sysopen -w -o cloexec,sync -u req_fd /tmp/gitstatus.1425.req.1579080686.1897628307.13117
    +gitstatus_start_impl:71> sysopen -r -o cloexec -u resp_fd /tmp/gitstatus.1425.resp.1579080686.1897997856.13973
    +gitstatus_start_impl:68> /usr/bin/zsh -dfmxc 'cd /; read; /usr/bin/setsid /usr/bin/zsh -dfxc $'\''\n'\''\ \ \ \ \ \ \ \ exec\ \>\&4$'\''\n'\''\ \ \ \ \ \ \ \ echo\ \$\$$'\''\n'\''\ \ \ \ \ \ \ \ /cygdrive/c/Users/k.graefe/dotfiles/shell/powerlevel10k/gitstatus/bin/gitstatusd-cygwin_nt-10.0-x86_64\ --lock-fd=3\ --parent-pid=1425\ --num-threads=12\ --max-num-staged=-1\ --max-num-unstaged=-1\ --max-num-conflicted=-1\ --max-num-untracked=-1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ \ \ if\ \[\[\ \$\?\ \!=\ \(0\|10\)\ \&\&\ \$\?\ -le\ 128\ \&\&\ -f\ /cygdrive/c/Users/k.graefe/dotfiles/shell/powerlevel10k/gitstatus/bin/gitstatusd-cygwin_nt-10.0-x86_64-static\ \]\]\;\ then$'\''\n'\''\ \ \ \ \ \ \ \ \ \ /cygdrive/c/Users/k.graefe/dotfiles/shell/powerlevel10k/gitstatus/bin/gitstatusd-cygwin_nt-10.0-x86_64-static\ --lock-fd=3\ --parent-pid=1425\ --num-threads=12\ --max-num-staged=-1\ --max-num-unstaged=-1\ --max-num-conflicted=-1\ --max-num-untracked=-1\ --dirty-max-index-size=-1\ --log-level=DEBUG$'\''\n'\''\ \ \ \ \ \ \ \ fi$'\''\n'\''\ \ \ \ \ \ \ \ echo\ -nE\ \$\'\''bye\\x1f0\\x1e\'\'' &!; rm -f /tmp/gitstatus.1425.req.1579080686.1897628307.13117 /tmp/gitstatus.1425.resp.1579080686.1897997856.13973 /tmp/gitstatus.1425.lock.1579080686.1888432503.4060'
    +gitstatus_start_impl:72> echo -nE $'0\nhello\C-_\C-^'
    +gitstatus_start_impl:75> ((  async  ))
    +gitstatus_start_impl:76> daemon_pid=-1
    +gitstatus_start_impl:109> ((  ! stderr_fd  ))
    +gitstatus_start_impl:110> unsetopt xtrace
    +gitstatus_start_impl:6> ((  daemon_pid == -1  ))
    +gitstatus_start_impl:75> ((  async  ))
    +gitstatus_start_impl:78> local reply IFS=''
    +gitstatus_start_impl:79> read -ru 22 reply
                               ^ this command failed

  The content of /tmp/gitstatus.1425.daemon-log.1579080686.1865808964.6808 (gitstatus daemon log):

    +zsh:1> cd /
    +zsh:1> read
    +zsh:1> rm -f /tmp/gitstatus.1425.req.1579080686.1897628307.13117 /tmp/gitstatus.1425.resp.1579080686.1897997856.13973 /tmp/gitstatus.1425.lock.1579080686.1888432503.4060
    +zsh:1> /usr/bin/setsid /usr/bin/zsh -dfxc $'\n        exec >&4\n        echo $$\n        /cygdrive/c/Users/k.graefe/dotfiles/shell/powerlevel10k/gitstatus/bin/gitstatusd-cygwin_nt-10.0-x86_64 --lock-fd=3 --parent-pid=1425 --num-threads=12 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --log-level=DEBUG\n        if [[ $? != (0|10) && $? -le 128 && -f /cygdrive/c/Users/k.graefe/dotfiles/shell/powerlevel10k/gitstatus/bin/gitstatusd-cygwin_nt-10.0-x86_64-static ]]; then\n          /cygdrive/c/Users/k.graefe/dotfiles/shell/powerlevel10k/gitstatus/bin/gitstatusd-cygwin_nt-10.0-x86_64-static --lock-fd=3 --parent-pid=1425 --num-threads=12 --max-num-staged=-1 --max-num-unstaged=-1 --max-num-conflicted=-1 --max-num-untracked=-1 --dirty-max-index-size=-1 --log-level=DEBUG\n        fi\n        echo -nE $\'bye\\x1f0\\x1e\''

  Your system information:

    zsh:      5.5.1
    uname -a: CYGWIN_NT-10.0 KG 3.1.2(0.340/5/3) 2019-12-21 15:25 x86_64 Cygwin

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new
```

**Comment by romkatv** [comment] 2020-01-16 11:51
I was unable to reproduce. Since this happens only occasionally on your system, there must be a race condition somewhere. I've tried adding `sleep 1` in various places of gitstatus initialization but still couldn't trigger the error.

We can see from the log that `/usr/bin/setsid /usr/bin/zsh -dfxc 'echo $$'` never reaches `echo $$`. Maybe there is something wrong with `setsid`? I've created branch `debug-gitstatus-94` in powerlevel10k where I've removed the call to `setsid`. Please try it and see if it helps.

```zsh
git -C /cygdrive/c/Users/k.graefe/dotfiles/shell/powerlevel10k pull
git -C /cygdrive/c/Users/k.graefe/dotfiles/shell/powerlevel10k checkout debug-gitstatus-94
```

If the error doesn't disappear, please post the content of `~/.zshrc`, `~/.zshenv`, `.zprofile` and `~/.zlogin` (some of these files may be missing).

**Comment by kgraefe** [comment] 2020-01-20 11:20
Will do, thanks.

It is hard for me to get what's happening there. But from the comment you edited in https://github.com/romkatv/powerlevel10k/commit/3c45a6740526c0dffa1b8ab1f414b6f4b6216cb8 it's doing a double fork. So it might be caused by [fork() being a slow operation on Cygwin][1]?

[1]: https://www.cygwin.com/faq.html#faq.api.fork

**Comment by romkatv** [comment] 2020-01-20 11:22
I know that fork is slower on Windows than on Linux. This doesn't explain the issue you are having. Please do try what I suggested earlier.

**Comment by kgraefe** [comment] 2020-01-28 10:55
Since I use `debug-gitstatus-94` the error did not occur.

I got ill last week, so I spend less time on my computer, but I feel like with `master` it would have happen at least a few times. I'll keep watching.

**Comment by romkatv** [comment] 2020-01-28 11:03
Thanks for the update. I've merged `debug-gitstatus-94` branch into `master`. Please switch to `master`.

```zsh
git -C /cygdrive/c/Users/k.graefe/dotfiles/shell/powerlevel10k checkout master
git -C /cygdrive/c/Users/k.graefe/dotfiles/shell/powerlevel10k pull
```

Please reopen this issue if you see the error again.

**Closed by romkatv** 2020-01-28 11:03 UTC
