### ISSUE TITLE
"gitstatus_query:echo:32: write error: broken pipe" after every command in zsh

### ISSUE THREAD

**Issue by HarrisonWilde** [romkatv/gitstatus#69] opened 2019-10-12 21:27 UTC
Since updating to Mac OS Catalina, I have been getting the following error:
`gitstatus_query:echo:32: write error: broken pipe`
every time I execute a command in my zsh shell. Upon restarting the issue is fixed but then reappears after what seems to be a random number of commands.

**Comment by romkatv** [comment] 2019-10-13 07:58
Thanks for the bug report.

I'll need your help to figure out what's causing this error. Please do the following:

1. Update powerlevel10k to the latest version.
2. Run this command:
```zsh
git clone --depth=1 https://github.com/romkatv/gitstatus.git ~/gitstatus
echo 'GITSTATUS_LOG_LEVEL=DEBUG' >>! ~/.zshrc
echo 'POWERLEVEL9K_GITSTATUS_DIR=~/gitstatus' >>! ~/.zshrc
```
3. Restart zsh.
4. If this gets rid of the error, please post a comment on the issue to let me know.
5. Once you see `broken pipe` error again, type the following command without changing your current directory and attach `~/p10k.log` to this issue.
```zsh
() {
  emulate -L zsh
  setopt xtrace
  typeset -pm 'POWERLEVEL9K_*|*GITSTATUS*|ZSH_VERSION|ZSH_PATCHLEVEL'
  uname -a
  pwd
  git status
  cat $GITSTATUS_DAEMON_LOG_POWERLEVEL9K
  cat $GITSTATUS_XTRACE_POWERLEVEL9K
} &>~/p10k.log
```

**Comment by HarrisonWilde** [comment] 2019-10-13 09:03
Thank you for the quick response, I followed steps 1-3 and so far haven't encountered any errors where I believe one would have appeared in the time I've spent. I will continue to monitor and follow the later steps if it ever does reappear.

**Comment by romkatv** [comment] 2019-10-13 09:08
That's good to know.

You can try commenting out `POWERLEVEL9K_GITSTATUS_DIR` in your `~/.zshrc`. If this makes the error reappear, it means the issue is caused by a bug that I've fixed in gitstatusd but haven't yet pushed the fix to powerlevel10k. With `POWERLEVEL9K_GITSTATUS_DIR` defined you are using the newest version of gitstatusd that has the fix.

If you can confirm my hunch, I'll push the fix to powerlevel10k.

**Comment by HarrisonWilde** [comment] 2019-10-13 09:22
Have just done as you said but can't seem to reproduce the error, will keep monitoring throughout the day though.

**Comment by romkatv** [comment] 2019-10-19 14:50
I've pushed gitstatus fixes to powerlevel10k. Please update it. You can remove `GITSTATUS_LOG_LEVEL` and `POWERLEVEL9K_GITSTATUS_DIR` from `~/.zshrc` and delete `~/gitstatus`. Please reopen if you are still seeing errors after doing this.

**Closed by romkatv** 2019-10-19 14:50 UTC
