### ISSUE TITLE
high cpu usage on debian/sid during idle

### ISSUE THREAD

**Issue by verfriemelt-dot-org** [romkatv/gitstatus#264] opened 2021-09-17 13:23 UTC
i noticed some high cpu load and therefore a high battery drain from gitstatus

![image](https://user-images.githubusercontent.com/1136869/133789350-1af06a10-bf57-4bf5-be26-8022e431768d.png)

those numbers are quite steady even with no refresh or inaction with the shell spawning the process to inspect the current repository ( the example given was using the postgresql repository https://github.com/postgres/postgres )

anything to check for?

**Comment by romkatv** [comment] 2021-09-17 13:26
Which shell are you using?

How are you using gitstatus from your shell?

**Comment by verfriemelt-dot-org** [comment] 2021-09-17 13:29
`zsh 5.8 (x86_64-debian-linux-gnu)` i checked the repo out to `~/src/` and source it via

```
source ~/src/gitstatus/gitstatus.prompt.zsh
```

**Comment by romkatv** [comment] 2021-09-17 13:39
Add this line to `.zshrc` prior to sourcing `gitstatus.prompt.zsh`:

```zsh
GITSTATUS_LOG_LEVEL=DEBUG
```

Then close all open shells and open one new shell. You should now have just one `gitstatusd` process and you should see `-v DEBUG` in its arguments instead of `-v FATAL` that you had before.

Open another shell and run `exec zsh -f` in it. This is to have a second shell without `gitstatusd`.

`cd` to the problematic git repo in the first shell (the one with `gitstatusd`). Wait 60 seconds. Using the second shell, check how much CPU time `gitstatusd` has consumed. Wait another 60 seconds and check again. If the difference is small, you aren't hitting the same issue as before, so you'll need to figure out what to do to induce `gitstatusd` to start consuming a lot of CPU at idle. Once you succeed, look at the logs by typing the following command in the first shell:

```zsh
less -- $GITSTATUS_DAEMON_LOG_MY
```

If it's not enlightening, attach it to this issue so that I can take a look.

**Comment by verfriemelt-dot-org** [comment] 2021-09-17 14:29
mhmm, okay, i figured it out, my prompt updates every second to refresh date and status of the repository. since its quite faster on smaller repositories, i didnt notice the resource consumption.

i used https://github.com/olivierverdier/zsh-git-prompt before, which took quite some time to refresh the prompt, hence i found your project. i read it through and thought, that the advertised speed increase would solve this issue for me.

this is the cpu time for 60 secounds, which equates roughly to 1.5sec cpu time per "update". 

![image](https://user-images.githubusercontent.com/1136869/133795422-055c24f6-7652-4f15-a5ba-c0d240106170.png)

i had some assumptions of the inner workings of this project, which turned out to be false.
for example i figured, there would be at most one gitstatusd instance per repository.
because if i have for example 5 shells in a tmux session open, this will result in about 50% cpu usage overall just for refreshing shells.

a git status in the affected repository seem to use way less resources:

```
$ time git status >/dev/null

real    0m0.032s
user    0m0.014s
sys     0m0.037s
```

so i suspect something else might be off.

this are the timings reported by the debug log:

```
[2021-09-17 16:04:34 00007fb155978c38 INFO src/response.cc:69] Replying with git status
[2021-09-17 16:04:34 00007fb155978c38 INFO src/timer.cc:67] Timing for: request: 1623.78ms cpu, 294.673ms wall
[2021-09-17 16:04:34 00007fb155978c38 INFO src/gitstatus.cc:204] Successfully processed request: "1631887474.1562192440 " for "/home/easteregg/src/postgres/"
```

**Comment by romkatv** [comment] 2021-09-17 14:34
> my prompt updates every second

So gitstatusd that has consumed a lot of CPU time on your first screenshot wasn't idle. It was computing git status of a postgres repository every second.

I suggest to close this issue as it's working as intended. Feel free to open another issue if there is anything else wrong with gitstatus from your point of view.

**Comment by verfriemelt-dot-org** [comment] 2021-09-17 14:35
mhmm, i reverted the debug options back to fatal and noticed, that now everything is back to "normal" as in sub 8% cpu usage per update?

i will keep an eye on this but for now, it seem to work just fine?? 

same repo as before, nothing changed.

```
[2021-09-17 16:34:45 00007fc7f25f4c38 INFO src/response.cc:69] Replying with git status
[2021-09-17 16:34:45 00007fc7f25f4c38 INFO src/timer.cc:67] Timing for: request: 115.586ms cpu, 45.4459ms wall
[2021-09-17 16:34:45 00007fc7f25f4c38 INFO src/gitstatus.cc:204] Successfully processed request: "1631889285.3272559643 " for "/home/easteregg/src/postgres/"
```

i am confused.

**Comment by verfriemelt-dot-org** [comment] 2021-09-17 14:36
> So gitstatusd that has consumed a lot of CPU time on your first screenshot wasn't idle. It was computing git status of a postgres repository every second.

correct, that was wrong.

the question which remains, what caused the high cpu usage during this timeperiod as pointed out in the logs i appended.

**Comment by romkatv** [comment] 2021-09-17 14:36
Things are faster when not logging a ton of crap. No mystery there.

**Comment by verfriemelt-dot-org** [comment] 2021-09-17 14:37
the last log was from debug mode aswell.

**Comment by romkatv** [comment] 2021-09-17 14:38
Then it could be many things. Hard to say from these short snippets. If you believe something is slower, list exact steps and attach a full log.

**Comment by romkatv** [comment] 2021-09-17 14:39
Closing because this issue is resolved. gitstatusd in question wasn't idle.

**Closed by romkatv** 2021-09-17 14:39 UTC
