### ISSUE TITLE
gitstatus failed to initialize on FreeBSD 8.3

### ISSUE THREAD

**Issue by vanyasvl** [romkatv/gitstatus#104] opened 2020-02-20 11:03 UTC
gitstatus failed to initialize on FreeBSD 8.3

See log attached
[gistatus_freebsd.log](https://github.com/romkatv/gitstatus/files/4230326/gistatus_freebsd.log)

**Comment by romkatv** [comment] 2020-02-20 11:05
Does it fail instantly or after 5 seconds?

**Comment by vanyasvl** [comment] 2020-02-20 12:00
After 5sec

**Comment by romkatv** [comment] 2020-02-20 12:13
Did it every work on this machine or has it stopped working?

Does it always fail or does it sometimes succeed?

I see that your temporary directory is under your home directory. Which filesystem is it on? Is there anything unusual about it?

Please run the following command and attach `${TMPDIR:-/tmp}/gitstatus.test.txt` to this issue when it completes (you can drag-and-drop files to the edit box on github).

```zsh
() {
  emulate -L zsh
  setopt err_return no_unset xtrace no_monitor
  zmodload zsh/system zsh/datetime

  local lock_file req_fifo resp_fifo
  local -i lock_fd=-1 daemon_pid=-1 req_fd=-1 resp_fd=-1
  local -F start_time=EPOCHREALTIME

  {
    lock_file=${TMPDIR:-/tmp}/gitstatus.test.lock.$$
    print -n >$lock_file
    zsystem flock -f lock_fd $lock_file
    req_fifo=${TMPDIR:-/tmp}/gitstatus.test.req_fifo.$$
    resp_fifo=${TMPDIR:-/tmp}/gitstatus.test.resp_fifo.$$
    mkfifo $req_fifo
    mkfifo $resp_fifo

    local cmd=$'
      echo $$
      read -t1 -rd "\x1e" msg
      echo -nE "${msg}\x1e"'
    cmd="cd /; zsh -dfxeuc ${(q)cmd} &!"
    zsh -dfmxeuc $cmd <$req_fifo >$resp_fifo 3<$lock_file &!

    sysopen -w -o cloexec,sync -u req_fd $req_fifo
    sysopen -r -o cloexec -u resp_fd $resp_fifo
    read -u $resp_fd daemon_pid
    rm -f $req_fifo $resp_fifo $lock_file

    function on-resp-hook() {}
    zle -F $resp_fd on-resp-hook

    local reply IFS=''
    echo -nE $'hello\x1f\x1e' >&$req_fd
    read -t2 -rd $'\x1e' -u $resp_fd reply
    [[ $reply == $'hello\x1f' ]]
    echo -E - SUCCESS
  } always {
    unsetopt err_return
    echo -E - took $((EPOCHREALTIME - start_time))s
    (( resp_fd    > 0 )) && { zle -F $resp_fd; exec {resp_fd}>&- }
    (( req_fd     > 0 )) && exec {req_fd}>&-
    (( lock_fd    > 0 )) && zsystem flock -u $lock_fd
    (( daemon_pid > 0 )) && kill -- -$daemon_pid &>/dev/null
    (( $+functions[on-resp-hook] )) && unfunction on-resp-hook
    rm -f $lock_file $req_fifo $resp_fifo
  }
} &>${TMPDIR:-/tmp}/gitstatus.test.txt
```

**Comment by vanyasvl** [comment] 2020-02-20 12:29
Did it ever work on this machine or has it stopped working?
I've tried powerlevel10k theme on this machine yesterday and it has an issue from very begining

Does it always fail or does it sometimes succeed?
Sometimes succed

I see that your temporary directory is under your home directory. Which filesystem is it on? Is there anything unusual about it?
UFS filesystem

`+(anon):3> zmodload zsh/system zsh/datetime
+(anon):5> local lock_file req_fifo resp_fifo
+(anon):6> local -i lock_fd=-1 daemon_pid=-1 req_fd=-1 resp_fd=-1
+(anon):7> local -F start_time=EPOCHREALTIME
+(anon):10> lock_file=/home/sid/tmp/gitstatus.test.lock.92179
+(anon):11> print -n
+(anon):12> zsystem flock -f lock_fd /home/sid/tmp/gitstatus.test.lock.92179
+(anon):13> req_fifo=/home/sid/tmp/gitstatus.test.req_fifo.92179
+(anon):14> resp_fifo=/home/sid/tmp/gitstatus.test.resp_fifo.92179
+(anon):15> mkfifo /home/sid/tmp/gitstatus.test.req_fifo.92179
+(anon):16> mkfifo /home/sid/tmp/gitstatus.test.resp_fifo.92179
+(anon):18> local cmd=$'\n      echo $$\n      read -t1 -rd "\C-^" msg\n      echo -nE "${msg}\C-^"'
+(anon):22> cmd='cd /; zsh -dfxeuc $'\''\n'\''\ \ \ \ \ \ echo\ \$\$$'\''\n'\''\ \ \ \ \ \ read\ -t1\ -rd\ \"$'\''\036'\''\"\ msg$'\''\n'\''\ \ \ \ \ \ echo\ -nE\ \"\$\{msg\}$'\''\036'\''\" &!'
+(anon):25> sysopen -w -o cloexec,sync -u req_fd /home/sid/tmp/gitstatus.test.req_fifo.92179
+(anon):26> sysopen -r -o cloexec -u resp_fd /home/sid/tmp/gitstatus.test.resp_fifo.92179
+(anon):27> read -u 17 daemon_pid
+(anon):23> zsh -dfmxeuc 'cd /; zsh -dfxeuc $'\''\n'\''\ \ \ \ \ \ echo\ \$\$$'\''\n'\''\ \ \ \ \ \ read\ -t1\ -rd\ \"$'\''\036'\''\"\ msg$'\''\n'\''\ \ \ \ \ \ echo\ -nE\ \"\$\{msg\}$'\''\036'\''\" &!'
+zsh:1> cd /
+zsh:1> zsh -dfxeuc '
      echo $$
      read -t1 -rd "^^" msg
      echo -nE "${msg}^^"'
+zsh:2> echo 92183
+zsh:3> read -t1 -rd ^^ msg
+(anon):28> rm -f /home/sid/tmp/gitstatus.test.req_fifo.92179 /home/sid/tmp/gitstatus.test.resp_fifo.92179 /home/sid/tmp/gitstatus.test.lock.92179
+(anon):31> zle -F 17 on-resp-hook
+(anon):33> local reply IFS=''
+(anon):34> echo -nE $'hello\C-_\C-^'
+(anon):35> read -t2 -rd $'\C-^' -u 17 reply
+zsh:4> echo -nE hello^_^^
+(anon):36> [[ $'hello\C-_' == hello^_ ]]
+(anon):37> echo -E - SUCCESS
SUCCESS
+(anon):39> unsetopt err_return
+(anon):40> echo -E - took 0.02061152458190918s
took 0.02061152458190918s
+(anon):41> ((  resp_fd    > 0  ))
+(anon):41> zle -F 17
+(anon):42> ((  req_fd     > 0  ))
+(anon):43> ((  lock_fd    > 0  ))
+(anon):43> zsystem flock -u 15
+(anon):44> ((  daemon_pid > 0  ))
+(anon):44> kill -- -92183
+(anon):45> ((  1  ))
+(anon):45> unfunction on-resp-hook
+(anon):46> rm -f /home/sid/tmp/gitstatus.test.lock.92179 /home/sid/tmp/gitstatus.test.req_fifo.92179 /home/sid/tmp/gitstatus.test.resp_fifo.92179`

**Comment by romkatv** [comment] 2020-02-20 12:41
> Sometimes succed

How often?

Since gitstatus startup sometimes succeeds and sometimes fails, let's run the test command 100 times. Please run the following command and attach `${TMPDIR:-/tmp}/gitstatus.test.txt` to this issue when it completes.

```zsh
() {
  emulate -L zsh
  local -i i
  for i in {1..100}; do
    () {
      echo starting run $i
      setopt err_return no_unset xtrace no_monitor
      zmodload zsh/system zsh/datetime

      local lock_file req_fifo resp_fifo
      local -i lock_fd=-1 daemon_pid=-1 req_fd=-1 resp_fd=-1
      local -F start_time=EPOCHREALTIME

      {
        lock_file=${TMPDIR:-/tmp}/gitstatus.test.lock.$$
        print -n >$lock_file
        zsystem flock -f lock_fd $lock_file
        req_fifo=${TMPDIR:-/tmp}/gitstatus.test.req_fifo.$$
        resp_fifo=${TMPDIR:-/tmp}/gitstatus.test.resp_fifo.$$
        mkfifo $req_fifo
        mkfifo $resp_fifo

        local cmd=$'
          echo $$
          read -t1 -rd "\x1e" msg
          echo -nE "${msg}\x1e"'
        cmd="cd /; zsh -dfxeuc ${(q)cmd} &!"
        zsh -dfmxeuc $cmd <$req_fifo >$resp_fifo 3<$lock_file &!

        sysopen -w -o cloexec,sync -u req_fd $req_fifo
        sysopen -r -o cloexec -u resp_fd $resp_fifo
        read -u $resp_fd daemon_pid
        rm -f $req_fifo $resp_fifo $lock_file

        function on-resp-hook() {}
        zle -F $resp_fd on-resp-hook

        local reply IFS=''
        echo -nE $'hello\x1f\x1e' >&$req_fd
        read -t1 -rd $'\x1e' -u $resp_fd reply
        [[ $reply == $'hello\x1f' ]]
        echo -E - SUCCESS
      } always {
        local err=$?
        unsetopt err_return
        echo finished run $i with status $err
        echo -E - took $((EPOCHREALTIME - start_time))s
        (( resp_fd    > 0 )) && { zle -F $resp_fd; exec {resp_fd}>&- }
        (( req_fd     > 0 )) && exec {req_fd}>&-
        (( lock_fd    > 0 )) && zsystem flock -u $lock_fd
        (( daemon_pid > 0 )) && kill -- -$daemon_pid &>/dev/null
        (( $+functions[on-resp-hook] )) && unfunction on-resp-hook
        rm -f $lock_file $req_fifo $resp_fifo
      }
    }
  done
  df -ThP ${TMPDIR:-/tmp}
} &>${TMPDIR:-/tmp}/gitstatus.test.txt
```

**Comment by vanyasvl** [comment] 2020-02-20 12:48
How often?

**Comment by vanyasvl** [comment] 2020-02-20 12:49
How often?
about 20-30% of failure

[gitstatus.test.txt](https://github.com/romkatv/gitstatus/files/4230749/gitstatus.test.txt)

**Comment by romkatv** [comment] 2020-02-20 12:55
Thanks for the info.

To be frank, I won't be looking into this any time soon. Failures of this sort, which only one person can reproduce, usually take on the order of 40-100 work-hours to debug. If you can debug this locally and give me more info, I'll dig into it. Otherwise I'll keep it on the back burner. There is a chance this issue will get resolved by itself when I replace daemonization code in gitstatus with an alternative approach that is currently used by powerlevel10k. I'll ping back to ask whether it indeed has helped.

**Comment by romkatv** [comment] 2020-02-24 11:30
> There is a chance this issue will get resolved by itself when I replace daemonization code in gitstatus with an alternative approach that is currently used by powerlevel10k. I'll ping back to ask whether it indeed has helped.

This is done. Please [update powerlevel10k to the latest version](https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-update-powerlevel10k) and restart zsh. Does it make it better/worse?

**Comment by vanyasvl** [comment] 2020-02-24 11:54
Nothing changes. I've started zsh 10 times and get error twice. So I have 80% success of gitstatus initialization.

**Comment by romkatv** [comment] 2020-02-24 12:07
That's unfortunate.

When initialization succeeds, it always completes quickly, but when it fails it takes 5 seconds, right?

Let's try another test. Please run the following command and attach `${TMPDIR:-/tmp}/gitstatus.test.txt` to this issue when it completes.

```zsh
() (
  emulate -L zsh -o err_return
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
  {
    cd $tmp
    git init
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
    >.zshrc <<\END
source $ZDOTDIR/powerlevel10k/config/p10k-pure.zsh
source $ZDOTDIR/powerlevel10k/powerlevel10k.zsh-theme
END
    repeat 100 ZDOTDIR=$tmp zsh -is <<<''
  } always {
    cd /
    rm -rf $tmp
  }
) &>${TMPDIR:-/tmp}/gitstatus.test.txt
```

It might take up to 10 minutes.

**Comment by vanyasvl** [comment] 2020-02-24 12:18
> When initialization succeeds, it always completes quickly, but when it fails it takes 5 seconds, right?
right

[gitstatus.test.txt](https://github.com/romkatv/gitstatus/files/4244491/gitstatus.test.txt)

**Comment by romkatv** [comment] 2020-02-24 12:32
Fascinating.

I've made a reasonable attempt at debugging this but unfortunately had no success. FreeBSD 8.3 is so old, I don't feel obligated to support it. Closing as *won't fix*. If you ever dig out more details, feel free to ping this issue.

**Closed by romkatv** 2020-02-24 12:32 UTC
